### ISSUE TITLE
Support for Slevomat CS 8.0

### ISSUE THREAD

**Issue by ondrejmirtes** [consistence-community/coding-standard#5]
Slevomat CS 8.0 has been released: https://github.com/slevomat/coding-standard/releases/tag/8.0.0

Please add support for it, thank you :)

**Comment by mhujer** [comment]
@ondrejmirtes I tagged it two days ago (https://github.com/consistence-community/coding-standard/releases/tag/3.11.2, but I pushed only the tag, not the master branch. Fixed it now. Thanks for the heads up!

**Comment by ondrejmirtes** [comment]
Thank you!
